version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: innovoBD
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./data:/data/db
      - ./data/log:/var/log/mongodb