import mongoose from "mongoose";
const trabajadorSchema=new mongoose.Schema({
    rut:{ 
        type:String,
        require:true,
        trim:true,
        unique:true
    },
    password:{
        type:String,
        require:true,
    },
    idsectores:{
        type:mongoose.Types.ObjectId,
        ref:'Sector',
        require:false
    },
    nombre:{
        type:String,
        require:true,
        trim:true
    },
    cargo:{
        type:String,
        enum:['Lector','Inspector','Administrador'],
        default:'Lector',
        require:true,
    },
    imgURL:{
        type:String,
        require:false,
    },
    contrato:{
        type:String,
        require:false,
    },
},{
    timestamps:true
})
export default mongoose.model('Trabajador',trabajadorSchema);